# Generated by Django 4.1.2 on 2022-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_alter_framework_rating_alter_language_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
